### ISSUE TITLE
No module named pointnet.relpn 

### ISSUE THREAD

**Issue by paulawulkop** [ShunChengWu/3DSSG#1]
I tried to run the toy example, but there was an error because there is no relpn.py file in the pointnet folder. Am I missing something, could you advise me on how to get it to run?
Thanks a lot!

**Comment by ShunChengWu** [comment]
Hey, thanks for trying out the code.
The relpn is actually not used. I will push a commit that cleans that out. 
We actually do not provide any example data since it involves leaking the dataset of 3RScan. 
If you would like to try it out you will need to go through the data generation pipeline.

**Comment by paulawulkop** [comment]
I see, thanks!
