### ISSUE TITLE
BUG report in ./utils/util_label.py

### ISSUE THREAD

**Issue by SgtVincent** [ShunChengWu/3DSSG#10]
Hi!

When running `gen_data.py` with `label_type` set to `ScanNet20`, I found a minor bug in L242-L243 of file `util_label.py': 
https://github.com/ShunChengWu/3DSSG/blob/9b9a55faf7cfcc4b59a7dbcadfca65c6f6d9300e/utils/util_label.py#L242

which should be changed to 
```
if nyu40name in label_names.values():
    id_scan20 = list(label_names.values()).index(nyu40name)+1
```

**Comment by ShunChengWu** [comment]
you are right! fixed.
thanks.

https://github.com/ShunChengWu/3DSSG/commit/a162ccf9851a30d757e6d81d9f7387ec3cac0f69
