### ISSUE TITLE
Preprocessed data

### ISSUE THREAD

**Issue by vivonicole** [ShunChengWu/3DSSG#11]
Hi,

Could you please release the preprocessed data? It is a bit complicated to preprocess the data... 

Thanks a lot.

**Comment by ShunChengWu** [comment]
Hi, 

we cannot provide the generated data directly due to the license issue of the 3RScan dataset. If you just want to try out this repo you can use the ground truth segmentation to generate the training data, which can bypass the step of generating estimate segment maps.
