### ISSUE TITLE
inseg.ply: how to get these files?

### ISSUE THREAD

**Issue by orsveri** [ShunChengWu/3DSSG#17]
Hi!
When I'm trying to run main.py to train on 3RScan, I get this error:

> ValueError: string is not a file: /3D/Datasets/1_3RScan/from_3DSSG/ab835faa-54c6-29a1-9b55-1a5217fcba19/inseg.ply

Apparently, `inseg.ply` file is needed, but I have only `semseg.v2.json`, `labels.instances.annotated.v2.ply` and `labels.instances.align.annotated.v2.ply` in the directory. What am I doing wrong?

(I downloaded 3RScan dataset, then used `gen_data_gt.py` script to prepare data. I assumed it is enough to run `main.py` and I don't need to do what is described in the next section, "Generate training/evaluation data from estimated segmentations". Am I right?)

Also as I understood, if I want to run your trained model, it's better to do it on the ScanNet dataset. Then how should I prepare the data? Use `gen_data_scannet.py` script?

**Comment by ShunChengWu** [comment]
The script `gen_data_gt.py` was written only to generate data with 160 classes. If you want to generate other label types, you can check 
https://github.com/ShunChengWu/3DSSG/blob/706703823cdfbd1e7d2d7b0bd659df88b71f563e/data_processing/gen_data.py#L492-L496
on how to modify `gen_data_pt.py`
