### ISSUE TITLE
Questions on trace mode

### ISSUE THREAD

**Issue by Lijin002** [ShunChengWu/3DSSG#18]
Hi!
I'm a student in Beijing and I have several questions on trace mode.
1. What does the _mode_ trace mean and what does it do?
2. When I try to run the command "python main.py --mode trace --config ./CVPR21/config_CVPR21.json", I meet an error as follows: 
 File "./src/dataset_SGFN.py", line 143, in __init__
    with open(os.path.join(self.root[0],'args.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sc/research/PersistentSLAM/python/3DSSG/data/3RScan_ScanNet20_InSeg_Full_20210430/args.json'
Strangely I cannot find the file "/sc" when I direct find files in the terminal, following the given path. Would you please tell me how to find where is wrong. (I followed the steps in README.txt of 3DSSG and I have downloaded and unzipped the pre-trained model "CVPR21")
I would appreciate it if you could reply.

**Comment by ShunChengWu** [comment]
Hi, 
1. trace mode is for tracing the python models to Onnx runtime files, which can then be used on the SceneGraphFusion framework ([repo](https://github.com/ShunChengWu/SceneGraphFusion)).
2.  The path is hardcoded. You should change it to your data folder.

**Comment by Lijin002** [comment]
Thank you for your reply!
Today I encounter a new problem: I tried the _eval_  mode to evaluate the trained model "CVPR21" using command:

python main.py --mode eval --config /home/flj/3DSSG/3DSSG-master/CVPR21/config_CVPR21.json

There is an error as showed below:

canno build eval dataset.
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    main()
  File "main.py", line 33, in main
    model = SGFN(config)                         
  File "/home/flj/3DSSG/3DSSG-master/src/SceneGraphFusionNetwork.py", line 67, in __init__
    self.model = SGFNModel(config,self.model_name,num_obj_class, num_rel_class).to(config.DEVICE)
**UnboundLocalError: local variable 'num_obj_class' referenced before assignment**

I haven't changed the codes, could you please tell me how to solve the problem and evaluate a model?
I would appreciate it if you could reply.

**Comment by ShunChengWu** [comment]
Probably because the system couldn't find the eval dataset. Check if you have `relationships_validation.json` and `validation_scans.txt` files in your dataset directory.

**Comment by Lijin002** [comment]
Thanks for your reply and your great work! I'll more carefully read /data_processing before bothering you.

**Comment by ShunChengWu** [comment]
no problems

**Comment by dhxxoo** [comment]
> Thank you for your reply! Today I encounter a new problem: I tried the _eval_ mode to evaluate the trained model "CVPR21" using command:
> 
> python main.py --mode eval --config /home/flj/3DSSG/3DSSG-master/CVPR21/config_CVPR21.json
> 
> There is an error as showed below:
> 
> canno build eval dataset. Traceback (most recent call last): File "main.py", line 83, in main() File "main.py", line 33, in main model = SGFN(config) File "/home/flj/3DSSG/3DSSG-master/src/SceneGraphFusionNetwork.py", line 67, in **init** self.model = SGFNModel(config,self.model_name,num_obj_class, num_rel_class).to(config.DEVICE) **UnboundLocalError: local variable 'num_obj_class' referenced before assignment**
> 
> I haven't changed the codes, could you please tell me how to solve the problem and evaluate a model? I would appreciate it if you could reply.

hi, i have the same problem right now. Did you solve this problem? If you did, could you please tell me how to deal with it? Really appreciate it.

**Comment by LydJason** [comment]
> 

Hi! I prepared 'ralationships_validation.json' and 'validation_scans.txt' and meet the same problem running eval when using 'config_example.json'. Did you solve this problem? If you did, may it be possible to tell me how to deal with it? Really appreciate it.
