### ISSUE TITLE
Question on generating evaluation data

### ISSUE THREAD

**Issue by Lijin002** [ShunChengWu/3DSSG#20]
Hi!
Sorry to bother you again, but I encountered another several questions during preparing evaluation data.

1. Follow "Generate training/evaluation data with GT segmentations", I directly run "gen_data_gt.py" and got an error: the following arguments are required: --pth_out
I add a path and try it again, another error is showed.
Detailed information is showed as the following picture. Could you please have a look on it and show me how to sucessfully generate evaluation data with GT segmentations?
![2021-12-02 21-41-52 的屏幕截图](https://user-images.githubusercontent.com/94791260/144446449-8fc2d0f0-81ed-405e-b304-50b41d9d8513.png)

2. I wonder whether it is enough to only run "gen_data_gt.py" if I merely wanna evaluate the given pre-trained network?

Looking forward to your reply.

**Comment by ShunChengWu** [comment]
1. You may need to check whether the input file exists or not. The error indicates that trimesh cannot load files at the given path `path_gt`. 
2. The pre-trained network doesn't use the GT segmentation as the input.

**Comment by Lijin002** [comment]
OK，I'll check my data-set. Sincerely thanks for you reply!
