### ISSUE TITLE
Questions on generate validation data

### ISSUE THREAD

**Issue by wzkwzk1998** [ShunChengWu/3DSSG#21]
Hi, I have a few questions about how to generate validation data with gt.

I've run "gen_data_gt.py" with three different types (train, test, validation), should I store the result in three folder.
    for example:
    `python gen_data_gt.py --type train --pth_out ../data/3RScan_train`
    `python gen_data_gt.py --type validation --pth_out ../data/3RScan_validation`
    `python gen_data_gt.py --type test--pth_out ../data/3RScan_test`
    are they correct? If not, what should I do?

**Comment by glennliu** [comment]
I tried the type 'eval' and generate the result to the same 'output' folder. It works fine for me.
Should be the same for other types.

**Comment by ShunChengWu** [comment]
you should generate them into the same output folder. 
Note that since there is no official test set in the dataset. You should `generate_train_valid_test_splits.py` to generate the train/validation/test split.

**Comment by wzkwzk1998** [comment]
thank you so much!
