### ISSUE TITLE
Curious about SGFN model learning.

### ISSUE THREAD

**Issue by qorgh346** [ShunChengWu/3DSSG#23]
Hello!
In the Scene Graph Fusion System (C++), the partial scene enters the input of the already learned model and then fuses the regional graph into a global graph on the system.
Question 1. It seems that the SGFN model in the 3DSSG provided does not enter the point cloud map for the partial scene, but enters the point cloud map for the entire scene, and then creates a local scene graph, right?

Question 2. Does the SGFN model in the 3DSSG provide not learn how to fuse, but to create a regional scene graph, and Scene Graph Fusion System (C++) creates a local scene graph when input into a partial scene, and fuses the result into a global scene graph through the algorithm proposed by the author?

**Comment by ShunChengWu** [comment]
Hi, 

The network never see partial scenes in the training time. But we do data augmentation to mimic the incomplete scene. That is why the network is able to handle partial scene at the end. 

Also, no fusion is learnt during training. We use the running average which is commonly use in reconstruction methods, such as Kinectfusion.
