### ISSUE TITLE
Some questions about relationships.txt

### ISSUE THREAD

**Issue by wzkwzk1998** [ShunChengWu/3DSSG#25]
According to the code, I think the relationships.txt shouldn't contain 'none'. Is that right?
But the relationships.txt I download using preparation.sh contain the 'none' relation.
Should I delete none in relationships.txt after run gen_data_gt.py

**Comment by ShunChengWu** [comment]
If I remember correctly, the `none` relationship may be needed in single predicate prediction but not needed in multiple predicate estimation. 
The data loader should handle both bases automatically. Further changes may not be needed.
