### ISSUE TITLE
I cannot access the files in "preparation.sh"...

### ISSUE THREAD

**Issue by timsu1104** [ShunChengWu/3DSSG#26]
I failed to run the wget commands in "preparation.sh". Besides, when I try to connect the links in "preparation.sh" directly, I received "404 Not Found" "nginx/1.18.0 (Ubuntu)" instead of the files. 
Has anyone encountered the same problem?

**Comment by ShunChengWu** [comment]
there may be a server issue. please check if the dataset provider
