### ISSUE TITLE
Split scene into subgraph

### ISSUE THREAD

**Issue by wtt0213** [ShunChengWu/3DSSG#28]
In the paper 3dssg, you split the scene into subgraph with 4-9 nodes, can you provide the script?

**Comment by wtt0213** [comment]
I just use the default param in gen_data_gt.py, but the node per item range from 2 to 40, not 4-9 in paper, obviously the relationship is mismatch
So can you provide the right param of the gen_data_gt script?

**Comment by ShunChengWu** [comment]
Please check this page: https://3dssg.github.io/
and ask the original author about that paper. They also provide a split training set.
Also please note that this code is not the original implementation of that paper.
