### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by xz-123-new** [ShunChengWu/3DSSG#33]
Thanks for your great work! I find it hard to download all the ply files from the given data link like  http://campar.in.tum.de/public_datasets/3RScan/Dataset//28298cd1-15b5-24be-8a19-49c0bf7c55b3/labels.instances.annotated.v2.ply since its quite unstable and slow to download by my side, could you please provide the data on online disk or some other download link? Thanks!

**Comment by xz-123-new** [comment]
Problem sovled.

**Comment by bowen-upenn** [comment]
May I ask how you solved the problem? Thanks.

**Comment by 123FCQ** [comment]
How did you solve this problem? Thank you.
