### ISSUE TITLE
Data splits

### ISSUE THREAD

**Issue by xz-123-new** [ShunChengWu/3DSSG#34]
Thanks for your great work! I want to reproduce the results of scene graph prediction using the gt segmentation which is shown in Table 1 in your paper, but since there is no official codebase for the original dataset 3DSSG, i can't access to the original data splits provided for this task, could you tell me how to generate them or where could i find it, thanks so much!

**Comment by ShunChengWu** [comment]
Unfortunately I cannot find the original split as well. But you can generate new one by running this script:
https://github.com/ShunChengWu/3DSSG/blob/master/data_processing/generate_train_valid_test_splits.py

Each scan has a "type". Use scan['type'] == 'train' for training and validation, and use scan['type'] == 'validation' for evaluation.
