### ISSUE TITLE
Question about use ScanNet dataset in Run_GenSeg.py

### ISSUE THREAD

**Issue by cbyan1003** [ShunChengWu/3DSSG#36]
Thanks for your great work!

I want to use ScanNet dataset to train this model.
When I follow the Run_GenSeg.py to generate InSeg.ply from ScanNet dataset. I found it needs a [[intrinsics.txt](https://github.com/ShunChengWu/SceneGraphFusion/blob/5bf9017c00949aedca1430854240667b3fa06565/libDataLoader/src/dataloader_scannet.cpp#LL34C62-L34C62)](https://github.com/ShunChengWu/SceneGraphFusion/blob/5bf9017c00949aedca1430854240667b3fa06565/libDataLoader/src/dataloader_scannet.cpp#LL34C62-L34C62) . 

But ScanNet dataset only provide scenexxx.txt, (like this in scene0709_00.txt)

`axisAlignment = 0.945519 0.325568 0.000000 -5.384390 -0.325568 0.945519 0.000000 -2.871780 0.000000 0.000000 1.000000 -0.064350 0.000000 0.000000 0.000000 1.000000 
colorHeight = 968
colorToDepthExtrinsics = 0.999973 0.006791 0.002776 -0.037886 -0.006767 0.999942 -0.008366 -0.003410 -0.002833 0.008347 0.999961 -0.021924 -0.000000 0.000000 -0.000000 1.000000
colorWidth = 1296
depthHeight = 480
depthWidth = 640
fx_color = 1170.187988
fx_depth = 571.623718
fy_color = 1170.187988
fy_depth = 571.623718
mx_color = 647.750000
mx_depth = 319.500000
my_color = 483.750000
my_depth = 239.500000
numColorFrames = 5578
numDepthFrames = 5578
numIMUmeasurements = 11834
sceneType = Apartment
`
I wonder how to generate intrinsics.txt, or could you tell me how to transfer from  scenexxx.txt?

**Comment by ShunChengWu** [comment]
Use this 
https://github.com/ScanNet/ScanNet/blob/master/SensReader/python/reader.py
to extract them.
