### ISSUE TITLE
How to setup a bigger BATCH_SIZE ?

### ISSUE THREAD

**Issue by PericlesHat** [ShunChengWu/3DSSG#37]
Thanks for your previous reply, I've successfully trained the model. 

I checked the GPU status when trainning and found the memory usage is not high enough. It shows `2GB/12GB` in my RTX 2080Ti. I want to speed up the process but I can't find a `batch_size` option in the config file. Is it proper to raise the values of all the `batch_size` in [SceneGraphFusionNetwork.py](https://github.com/ShunChengWu/3DSSG/blob/69ad0818daaf7229fa193aeff4a608a34c189139/src/SceneGraphFusionNetwork.py#L124)?

**Comment by ShunChengWu** [comment]
In short, you can't on this implementation. 
If you want you can change the data loader to https://pytorch-geometric.readthedocs.io/en/latest/modules/loader.html,
and modify the GNN part.
