### ISSUE TITLE
Question about 3DSSG method

### ISSUE THREAD

**Issue by IABAcademy** [ShunChengWu/3DSSG#40]
Thanks for your great work!
I have a question about your implementation of the method in 3DSSG.In Table 2,the results show that your method outperforms the method in 3DSSG.
![1680348949445](https://user-images.githubusercontent.com/65117056/229286403-5d6c9185-8493-46af-84d2-1bc15873a78b.jpg)

How can I reproduce the result in Table 2,using your code?And how should  I modify config_CVPR21.json to use the method in **3DSSG**?
Looking forward to your reply!

**Comment by IABAcademy** [comment]
> Thanks for your great work! I have a question about your implementation of the method in 3DSSG.In Table 2,the results show that your method outperforms the method in 3DSSG. ![1680348949445](https://user-images.githubusercontent.com/65117056/229286403-5d6c9185-8493-46af-84d2-1bc15873a78b.jpg)
> 
> How can I reproduce the result in Table 2,using your code?And how should I modify config_CVPR21.json to use the method in **3DSSG**? Looking forward to your reply!

I modified the config_CVPR21.json in your repo:
"MODEL": "SGPN","dataset_type": "SGPN","label_file": "labels.instances.align.annotated.v2.ply" and left the rest unchanged.
And I run the code using command:"python main.py --mode train--config ./config_CVPR21.json ",trained 100 epoches.
The recall for predicates look nothing like in Table 2.
![image](https://user-images.githubusercontent.com/65117056/229286834-18dbe4b5-521e-47fb-b564-4896510e2c32.png)
Is there any need to modify other hyperparameters?

**Comment by ShunChengWu** [comment]
I am currently occupied and will check this soon.

**Comment by ShunChengWu** [comment]
I have uploaded a config file for 3DSSG. But the defualt config is a bit different. 
You will need to adjust the config If you want to use the same hyperparameters as reported in the original paper.
