### ISSUE TITLE
Messagepassing in TripletGCN

### ISSUE THREAD

**Issue by ddsediri** [ShunChengWu/3DSSG#41]
Hi @ShunChengWu,

Thank you for the excellent implementation, great work! I was hoping you can clarify the message-passing scheme for the TripletGCN you have used. 

In the 3DSSG paper and the SG2IM paper, the processed features of each point cloud object is averaged separately for when it appears as a subject in a triplet or as an object. But, in line 64 of network_TripletGCN.py, you directly add the processed features of the subject point cloud and object point cloud together, for each triplet, after the triplets have been processed by nn1(.). Then you scatter_add along the index during aggregation. This is a bit different to the SG2IM implementation here: https://github.com/google/sg2im/blob/2c1bf4a150f8a70c0977200a6719519213367b5c/sg2im/graph.py.

Could you please clarify if this meant to be different from the SG2IM implementation or did I miss something?

Thank you very much!
D.

**Comment by ShunChengWu** [comment]
Hi, 

indeed, to be closer to the original implementation, you should pass aggre='mean' here: https://github.com/ShunChengWu/3DSSG/blob/69ad0818daaf7229fa193aeff4a608a34c189139/src/network_TripletGCN.py#L44

In 
https://github.com/google/sg2im/blob/2c1bf4a150f8a70c0977200a6719519213367b5c/sg2im/graph.py#L98C76-L99
they are not separately averaging over "in" and "out", they added all and then divided by all. 
This is similar to https://github.com/ShunChengWu/3DSSG/blob/69ad0818daaf7229fa193aeff4a608a34c189139/src/network_TripletGCN.py#L64
since each edge always contributes to 1 "in" and 1 "out". 

Our early experiment show no difference between using "mean" and "sum", but if you experience performance gap please let me know.

**Comment by ddsediri** [comment]
Hi @ShunChengWu ,

My query is more in reference to the second part of the reply and not the 'aggr' setting because if feature vectors are summed and divided appropriately, you do do recover the mean.

In https://github.com/google/sg2im/blob/2c1bf4a150f8a70c0977200a6719519213367b5c/sg2im/graph.py#LL98C1-L99C76, they scatter_add along the s_idx_exp first and then along the o_idx_exp. So in fact they are first summing over 'in' and 'out' and not over all. They obtain the average by dividing by the number of occurences. In the SG2IM implementation, they follow their paper where

**Comment by ShunChengWu** [comment]
I get your point. They sum the "in" and "out" nodes separately. But since an edge always includes one in and out node. 
In the end, they are all added together and then divided by the total number of object counts (if using "avg" pooling). 

Here is a simple code to show my understanding of the two implementations:
My version:
```
sum = torch.zeros_like(node_features)
for edge_index in edge_indices:
   sum += node_features[edge_index[0]]
   sum += node_features[edge_index[1]]
   # Or
   # sum += node_features[edge_index[0]] + node_features[edge_index[1]]
```
Their version
```
sum = torch.zeros_like(node_features)
for edge_index in edge_indices: # in/out
   sum += node_features[edge_index[0]]
for edge_index in edge_indices: # out/in
   sum += node_features[edge_index[1]]
```
But maybe I understand it wrongly. If you discover anything please let me know.

**Comment by ddsediri** [comment]
I think where the original formulation is different is that I don't think `all` node features are added together. Only the intermediate features (https://github.com/google/sg2im/blob/2c1bf4a150f8a70c0977200a6719519213367b5c/sg2im/graph.py#LL85C1-L89C56) where a given scene object/node is a `S` or an `O`, in a triple, contributes to its node feature, which is done using the scatter_add along s_idx_exp or o_idx_exp. So the node features of other objects should not contribute to the signal. I may be wrong but my understanding of the SG2IM code is similar to the following pseudocode:
```
sum_s = torch.zeros(N, D) # N is number of nodes, D is feature dimension
sum_o = torch.zeros(N, D) # N is number of nodes, D is feature dimension
obj_s_counts = torch.zeros(N) # N = number of nodes
obj_o_counts = torch.zeros(N) # N = number of nodes
for obj_idx in range(N):
   for idx, edge_index in enumerate(edge_indices): # in/out
      if obj_idx == edge_index[0]: # the scene object is an out (S)
         sum_s[obj_idx] += new_s_vecs[idx]
         obj_s_counts[obj_idx] += 1
      elif obj_idx == edge_index[1]: # the scene object is an in (O)
         sum_o[obj_idx] += new_o_vecs[idx]
         obj_o_counts[obj_idx] += 1
pooled_vecs = sum_s / obj_s_counts + sum_o / obj_o_counts
node_features = net2(pooled_vecs)
``` 
The key is it is not the `node_features` being summed but the intermediate `new_s_vecs` or `new_o_vecs` which have shape `(E, D)` with E the number of edges. 

By the way, I really appreciate the discussion on the issue. I think the TripletGCN is a very nice method for the SGG task. I'll try to get an implementation up with the original 3DSSG training splits so as to analyse any performance difference and update you on how that goes and if there is much of a difference.

**Comment by ShunChengWu** [comment]
You are right about the code I wrote, which should not be node_features. 
If you replace node_features with the intermediate node_feature then it should be it. 
This is the same as in the `def message` here:
https://github.com/ShunChengWu/3DSSG/blob/69ad0818daaf7229fa193aeff4a608a34c189139/src/network_TripletGCN.py#L58-L65
I can also write a simple code to show it but right now I am occupied by too much stuff.
Let me know how it goes with your implementation. 

Thanks!

**Comment by ddsediri** [comment]
Hey, thanks for replying even though it's a busy time. Unfortunately, I don't have the time to do the pre-processing and get the training testing splits to test the code either because things are a bit hectic. I've modified the message and aggregation functions to show the idea of scatter_adding only the intermediate features for the given object/instance as per SG2IM:
```
def message(self, x_i, x_j, edge_feature):
    x = torch.cat([x_i, edge_feature, x_j],dim=1)
    x = self.nn1(x) #.view(b,-1)
    new_x_i = x[:,:self.dim_hidden]
    new_e   = x[:,self.dim_hidden:(self.dim_hidden+self.dim_edge)]
    new_x_j = x[:,(self.dim_hidden+self.dim_edge):]
    # x = new_x_i + new_x_j
    return [new_x_i, new_x_j, new_e]

def aggregate(self, x: Tensor, edge_index: Tensor,
                insnum: Tensor, # number of nodes
                ptr: Optional[Tensor] = None,
                dim_size: Optional[int] = None) -> Tensor:
    cols = edge_index[0, :]
    rows = edge_index[1, :]
    new_x_i, new_x_j, new_e = x
    x1 = scatter(new_x_i, rows, dim=self.node_dim, dim_size=dim_size, reduce=self.aggr) # scatter add for the given instance if it is a subject in triple
    x2 = scatter(new_x_j, cols, dim=self.node_dim, dim_size=dim_size, reduce=self.aggr) # scatter add for the given instance if it is an object in triple
    x = (x1 + x2) /  (insnum - 1)
    return [x, new_e]
```
Will let you know how my implementation goes once I have it running. Good luck with your work!
