### ISSUE TITLE
Using predicted Scene Graphs For Segmentation

### ISSUE THREAD

**Issue by sayands** [ShunChengWu/3DSSG#42]
Hi, firstly thanks for your great work! 

I was trying out instance segmentation using the predicted scene graphs, aka, merging the segments with "same part" relationship. However, the predictions are like the following : triplets having been predicted with "same part" relationship do not belong to the same predicted semantic object class (which is not possible in reality and probably just bad predictions). I am not sure how to handle this and then generate instance maps from the over-segmented maps.

Could you please tell me how did handle segmentation while implementing the paper? It'd be very nice if you could share the code as well, if not, a short description will be amazing. Thank you very much. 

Regards, 
Sayan

**Comment by ShunChengWu** [comment]
What I did is by averaging the class distribution (softmax) when merging the parts. 
There is a simple implementation in the SceneGraphFusion repo https://github.com/ShunChengWu/SceneGraphFusion

**Comment by sayands** [comment]
Thanks for your response, I do not understand what exactly you mean. Would you kindly point me to the part of the code in the SceneGraphFusion repo?

**Comment by ShunChengWu** [comment]
it's a bit hard to understand in c++ code TBH:
https://github.com/ShunChengWu/SceneGraphFusion/blob/5bf9017c00949aedca1430854240667b3fa06565/libGraphSLAM/graphPredictor/GraphPredictor.cpp#L853
The idea is to take all the predictions from all the nodes that are connected with the "same part" relationship, then average them.

**Comment by sayands** [comment]
Thanks, this helps!
