### ISSUE TITLE
Question about pre-trained model results

### ISSUE THREAD

**Issue by k2room** [ShunChengWu/3DSSG#46]
Thank you for providing the updated code and pre-trained model! But I have several questions about it.

1) What's different between GT, DENSE, and SPARSE datasets? Could you please tell me where I can find the information about it?
2) Are the results of README a value of recall@1? 

Thank you!

**Comment by ShunChengWu** [comment]
1. The GT, Dense and Sparse refer to the experiment setup in [this paper](https://openaccess.thecvf.com/content/CVPR2023/papers/Wu_Incremental_3D_Semantic_Scene_Graph_Prediction_From_RGB_Sequences_CVPR_2023_paper.pdf) Sec. 4.2. 
2. Yes
Thanks
