### ISSUE TITLE
Test on scannet datasets

### ISSUE THREAD

**Issue by k2room** [ShunChengWu/3DSSG#49]
Hello, I want to create a 3D scene graph by testing the 3DSSG model on different datasets such as Scannet, and performing the inference process. Do you plan to provide an inference code or a Demo version of that code?
For 3RScan datasets in this repository, I can download and use pre-processed datasets already. However, if I use other datasets, It seems that data such as "color_align.ply" and "~.annotated.v2.ply", etc should be created. Can you tell me how the rendered data was generated?

Thanks for the nice work!

**Comment by ShunChengWu** [comment]
You can check the previous cvpr21 version of the code
https://github.com/ShunChengWu/3DSSG/tree/cvpr21
I don't see myself adding this feature in the near future.

**Comment by amalie-kjaer** [comment]
Hey @k2room :) I am also trying to extract 3D scene graphs of ScanNet, did you figure this out? If so could you offer some pointers on how to achieve this? Thanks!
