### ISSUE TITLE
Files for data preparation missing

### ISSUE THREAD

**Issue by SgtVincent** [ShunChengWu/3DSSG#5]
Hi, thanks for your great work! 

I am trying to run your code, but `preparation.sh`, `references.txt` and `rescans.txt` needed by data preparation are missing from the `./files` directory. 

Will you release these files? 

Thanks!

**Comment by ShunChengWu** [comment]
hi, 

I forgot to update the missing file "preparation.sh".
go to the files folder and run
`bash preparation.sh`
All other files should be downloaded by running this script
