### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by hq0709** [ShunChengWu/3DSSG#56]
Hi, thx for your great work.

I want to ask where is the related code according to the paper?
![8139a3158f914eab8ce8e444c2736e78](https://github.com/ShunChengWu/3DSSG/assets/101915811/aa895258-f9b3-4e49-af9d-7b0cfa2fc077)

Thank you very much

**Comment by ShunChengWu** [comment]
Hm... I think this equation extracts the union points of two given point sets. 
Check here:
https://github.com/ShunChengWu/3DSSG/blob/main/ssg/dataset/dataloader_SGFN.py#L840
