### ISSUE TITLE
RuntimeWarning Error

### ISSUE THREAD

**Issue by Bongnah** [ShunChengWu/3DSSG#61]
Hello,

thank you for the great work!

When proceeding with the training for 3RScan 160, the following error occurred.

home/3DSSG/ssg/utils/util_eva.py:1297: RuntimeWarning: invalid value encountered in divide
  return self.c_mat[:, 0] / (self.c_mat[:, 0]+self.c_mat[:, 2])

Maybe this error comes out because the value of TN diverges to infinity, but I don't know how to fix it because it didn't happen in 3RScan20.
When training, for SGPN_full_l160, the error is constant without decreasing from 5, and I would like to ask if it is related to this problem.

**Comment by ShunChengWu** [comment]
This shouldn’t be a problem. It’s a warning at the very beginning of the training when there is no output for certain classes. It can be avoided by adding some simple checks but I was not bothered to do so. Feel free to create a pull request if you would like to fix this bug. 
Best, 
Shun-Cheng Wu
