### ISSUE TITLE
About 3D OBB code

### ISSUE THREAD

**Issue by zhangzjjjjjj** [ShunChengWu/3DSSG#62]
Sorry to bother you, but I couldn't find any code related to 3D OBB generation in the current codebase. Could the author provide some information on this?

**Comment by zhangzjjjjjj** [comment]
And another question, does the boundary dimension of the OBB represent the half-length along the three axes, or the full length?
![1725265204325](https://github.com/user-attachments/assets/f4ddf0e5-8468-4303-9872-7bd9413fda07)
The image from semseg.v2.json

**Comment by ShunChengWu** [comment]
Here is the code where the bounding box is calculated with 3RScan input. I am not sure if I changed the OBB to radius or not  but from here it looks like diameter 3DSSG/data_processing/gen_data.py at 4b783ecdc6caba1515b361f8a0643d0c2d568f52 · ShunChengWu/3DSSGgithub.comShun-Cheng Wuzhangzjjjjjj ***@***.***> 於 2024年9月2日 10:21 寫道：﻿
And another question, does the boundary dimension of the OBB represent the half-length along the three axes, or the full length?
1725265204325.jpg (view on web)
The image from semseg.v2.json

**Comment by zhangzjjjjjj** [comment]
@ShunChengWu  Thank you very much for your prompt response. Regarding the second question, I also believe it should be the diameter, not the radius. As for the first question, I'm sorry I wasn't clear earlier. What I meant was, in the case of a sparse setting, the OBB annotations are obtained by directly extracting them from the 2dssg_orbslam3.json file, which is downloaded and unzipped from the link provided in the RUN_prepare_Sparse_setup_3RScan.py file: https://www.campar.in.tum.de/public_datasets/2023_cvpr_wusc/reconstruction_orbslam3.zip.

Since a pre-annotated file is used, an end-to-end implementation is not possible. Therefore, my question is, do you have any code or methods available to directly obtain the OBB annotations?

**Comment by ShunChengWu** [comment]
The axis-aligned oriented bounding boxes for the sparse and dense setup are obtained using the modified algorithm of ApproxMVBB, which you can get here: https://github.com/ShunChengWu/ApproxMVBB. 
There are also some instructions from the original author on how to use it.

**Comment by zhangzjjjjjj** [comment]
@ShunChengWu Thank you a lot !!!

**Comment by Howardkhh** [comment]
@ShunChengWu Hello! It seems like the mapping from predicted nodes to ground truth nodes for evaluating the recall metrics is also inferred from `2dssg_orbslam3.json` files. Based on my understanding, for a given predicted node, the corresponding ground truth node is determined by the occupancy ratio. Specifically, the values in the "gtInstance" field (as shown in the JSON snippet below) represent the occupancy ratios. If the highest occupancy ratio exceeds 0.5 (as specified in [configs/dataset
/config_base_3RScan_orbslam_l20.yaml](https://github.com/ShunChengWu/3DSSG/blob/4b783ecdc6caba1515b361f8a0643d0c2d568f52/configs/dataset/config_base_3RScan_orbslam_l20.yaml#L12)), the mapping between the predicted node and the ground truth node with the highest occupancy ratio is created.

```json
"nodes": {
           "0": {
               "center": [
            0.335639,
            0.499171,
           -0.063223
                   ],
               "color": [
                 255,
                 255,
                 255
                   ],
               "dimension": [
             5.93825,
             3.01395,
             2.43626
                   ],
               "gtInstance": {
                   "1": 0.0976331,
                   "10": 0.0857988,
                   "11": 0.0769231,
                   "12": 0.0236686,
                   "16": 0.00887574,
                   "17": 0.0769231,
                   "2": 0.0532544,
                   "20": 0.0325444,
                   "25": 0.0414201,
                   "26": 0.0266272,
                   "27": 0.0384615,
                   "28": 0.12426,
                   "29": 0.035503,
                   "3": 0.0295858,
                   "30": 0.056213,
                   "31": 0.0118343,
                   "35": 0.00295858,
                   "45": 0.00295858,
                   "47": 0.0266272,
                   "5": 0.00295858,
                   "6": 0.0207101,
                   "8": 0.00295858,
                   "9": 0.121302
                   },
               "kfs": [],
               "label": "unknown",
               "neighbors": [],
               "rotation": [
            0.788351,
           -0.615226,
                   0,
            0.615226,
            0.788351,
                   0,
                   0,
                   0,
                   1
                   ]
               }
        }
```

Could you clarify how the occupancy ratio is calculated? If possible, would you be able to share the code used for calculating the occlusion ratios?

Thank you in advanced!

**Comment by zhangzjjjjjj** [comment]
> The axis-aligned oriented bounding boxes for the sparse and dense setup are obtained using the modified algorithm of ApproxMVBB, which you can get here: https://github.com/ShunChengWu/ApproxMVBB. There are also some instructions from the original author on how to use it.

@ShunChengWu Sorry to bother you again. I have checked the repository you forked, but I couldn't find any modifications in the original code related to implementing gravity-aligned oriented bounding boxes. Regarding the code for gravity alignment, did you apply gravity alignment constraints beforehand, or did you make additional adjustments after obtaining the oriented bounding boxes to ensure gravity alignment? Would you happen to have any suggestions?

**Comment by ShunChengWu** [comment]
Ah true. I checked the code and did a workaround to get the axis-aligned bounding boxes. 
I treat the 3D points as in 2D and use the 2D methods to estimate the bounding boxes. 
Here is a snapshot of the code I have. 
```
        /*estimate in 2D*/
        ApproxMVBB::Matrix2Dyn points(2, n_pts);
        int counter = 0;
        float min_z=std::numeric_limits<float>::max(),max_z=std::numeric_limits<float>::lowest();
        for (const auto &ele: filtered_elements) {
            auto pt = ele->GetWorldPosEigen();
            for (int j = 0; j < 2; ++j)
                points(j, counter) = pt[j];
            if(pt[2]<min_z)min_z=pt[2];
            if(pt[2]>max_z)max_z=pt[2];
            counter++;
        }
        lock_ele.unlock();

        ApproxMVBB::MinAreaRectangle c(points);;
        c.compute();
        auto rect = c.getMinRectangle();
        auto min_cor = rect.m_p;
        Eigen::Vector2d max_cor = rect.m_p + rect.m_u * rect.m_uL + rect.m_v * rect.m_vL;
        for(int i=0;i<2;++i) {
            output.min[i] = min_cor[i];
            output.max[i] = max_cor[i];
        }
        output.min[2]=min_z;
        output.max[2]=max_z;


        Eigen::Matrix3d rot = Eigen::Matrix3d::Identity();
        auto angle_x = std::atan2(rect.m_u.y(),rect.m_u.x());
        rot = Eigen::AngleAxisd(angle_x, Eigen::Vector3d(0,0,1)).toRotationMatrix();
```
It's a mess, but I don't have time to clean it up. Hopefully, this helps.

**Comment by zhangzjjjjjj** [comment]
@ShunChengWu I apologize for missing your messages because Gmail did not notify me in time. This is sufficient, and I truly appreciate your help. My questions have been answered, so I will close this issue. Wishing you all the best with your work!
