### ISSUE TITLE
How Many Scene Reconstructions per Environment in 3DSSG? 2 Steps (Before-After) or Multiple Steps?

### ISSUE THREAD

**Issue by ilileun** [ShunChengWu/3DSSG#64]
I'm curious about how many reconstructions were made within a single environment in the 3DSSG dataset. The paper mentions 478 environments with 1482 3D reconstructions, so how many scenes were reconstructed per environment? Specifically, were the scene changes captured in a simple before-after manner, or were there multiple steps involved?

For example, object state changes could involve:

    State change: Objects turning on/off or becoming open/closed (e.g., toilet lid).
    Position change: Objects being moved, added, or removed (e.g., chairs, cushions).
    Tidiness change: Spaces becoming cleaner or messier (e.g., desk, bed).

Is the reconstruction based on just two states (before and after), or does it capture more stages of change?

Are there any reference codes or scripts available??

Thank you.

**Comment by ShunChengWu** [comment]
There are many states. Please check the dataset page for all the details. 
https://waldjohannau.github.io/RIO/
