### ISSUE TITLE
plydata = util_ply.load_rgb(path)

### ISSUE THREAD

**Issue by YYLiuDLUT** [ShunChengWu/3DSSG#7]
When I use the SGPN dataset and SGPN model, I tried to use the rgb information, but a lot of IndexError happened in function load_rgb in util_ply file. I really want to know how can I fix this problem.

**Comment by ShunChengWu** [comment]
one problem can be that you load the wrong files. 
please provide more the error message otherwise it is hard to know the issue

**Comment by yyliucch** [comment]
@ShunChengWu 
**This is the Error Info**
 File "/home/lyy/project/test/src/dataset_SGPN.py", line 251, in __getitem__
    data = load_mesh(path, self.mconfig.label_file, self.use_rgb, self.use_normal)
  File "/home/lyy/project/test/src/dataset_SGPN.py", line 58, in load_mesh
    plydata = util_ply.load_rgb(path)
  File "/home/lyy/project/test/utils/util_ply.py", line 98, in load_rgb
    label_mesh_align.visual.vertex_colors[i] = colors[idx[0]]
IndexError

**This is the Error Code**
`label_mesh_align = trimesh.load(pth_label, process=False)
    if pth_label != pth_label_raw:
        label_mesh = trimesh.load(pth_label_raw, process=False)
        import open3d as o3d
        query_points = label_mesh.vertices        
        if isinstance(mesh, trimesh.base.Trimesh):
            tree = o3d.geometry.KDTreeFlann(mesh.vertices.transpose())
            colors = trimesh.visual.uv_to_color(mesh.visual.uv,mesh.visual.material.image)
            print(colors.shape)
        else:
            colors = mesh.visual.vertex_colors
        
        if 'nx' not in label_mesh_align.metadata['ply_raw']['vertex']['data']:
            label_mesh_align.metadata['ply_raw']['vertex']['properties']['nx'] = '<f4'
            label_mesh_align.metadata['ply_raw']['vertex']['properties']['ny'] = '<f4'
            label_mesh_align.metadata['ply_raw']['vertex']['properties']['nz'] = '<f4'
            label_mesh_align.metadata['ply_raw']['vertex']['data']['nx'] = np.zeros([len(query_points),1],dtype=np.float32)
            label_mesh_align.metadata['ply_raw']['vertex']['data']['ny'] = np.zeros([len(query_points),1],dtype=np.float32)
            label_mesh_align.metadata['ply_raw']['vertex']['data']['nz'] = np.zeros([len(query_points),1],dtype=np.float32)
        print(len(query_points))
        for i in range(len(query_points)):
            if isinstance(mesh, trimesh.base.Trimesh):
                point = query_points[i]
                [k, idx, distance] = tree.search_radius_vector_3d(point,0.001)
            else:
                idx = [i]
            label_mesh_align.visual.vertex_colors[i] = colors[idx[0]]`

I print out the colors' shape and query_points' shape, it seems that the query_points is longer than the color shape
(30219, 4)
30221

This is how I define the Label file of 3RSCAN Dataset (ps: I only use 3RSCAN Dataset)
`# 3RScan file names
LABEL_FILE_NAME_RAW = 'labels.instances.annotated.v2.ply'
LABEL_FILE_NAME = 'labels.instances.align.annotated.v2.ply'
SEMSEG_FILE_NAME = 'semseg.v2.json'
MTL_NAME = 'mesh.refined.mtl'
OBJ_NAME = 'mesh.refined.v2.obj'
TEXTURE_NAME = 'mesh.refined_0.png'`

Thank you very much for answering my question, I really want to know how to fix this problem.

**Comment by ShunChengWu** [comment]
can you check what is the value of your `pth_obj`

if it ends with 'color.align.ply', then this means that the aligned ply file does not have the same number of vertices as the raw file. 
if it ends with 'mesh.refined.v2.obj', then it should have the exact same amount of vertices.

It is most likely the error from generating the aligned ply file.

**Comment by yyliucch** [comment]
I ran the transform_ply again and generated the aligned ply file, but it doesn't solve my problem.
And it seems that the points is loaded from the LABEL_FILE_NAME_RAW = 'labels.instances.annotated.v2.ply' file.
`    if pth_label != pth_label_raw:
        label_mesh = trimesh.load(pth_label_raw, process=False)
        import open3d as o3d
        query_points = label_mesh.vertices        
        if isinstance(mesh, trimesh.base.Trimesh):
            tree = o3d.geometry.KDTreeFlann(mesh.vertices.transpose())
            colors = trimesh.visual.uv_to_color(mesh.visual.uv,mesh.visual.material.image)
        else:
            colors = mesh.visual.vertex_colors`

When I changed the LABEL_FILE_NAME_RAW file as 'labels.instances.align.annotated.v2.ply', it will report the error below

  File "/home/lyy/threedsgg/utils/util_ply.py", line 106, in load_rgb
    label_mesh_align.visual.vertex_colors = mesh.visual.vertex_colors
AttributeError: 'TextureVisuals' object has no attribute 'vertex_colors'

**Comment by ShunChengWu** [comment]
I am not able to reproduce your error. I think this may have something to do with the version of trimesh. Are you using the exact environment setup as described in the readme file?

**Comment by ShunChengWu** [comment]
closed due to inactivity

**Comment by otakudj** [comment]
I also meet the same problem and i think i find the solution. 
Both @wtt0213 and author @ShunChengWu are right. The reason why return idx=[] is that the label_mesh and mesh have not exactly same vertices (as shown below). 
![image](https://user-images.githubusercontent.com/27484315/215244504-6feb681d-534e-419e-9cb9-4b7f1a05e799.png)
And it is because the version of trimesh is higher than the version written in the [environment.yaml](https://github.com/ShunChengWu/3DSSG/blob/69ad0818daaf7229fa193aeff4a608a34c189139/environment.yml#L12). The solution is to ensure your trimesh version is the same as the author inform(i.e. 3.9.13). Hope this can help you if you still have this problem @wtt0213 @YYLiuDLUT

**Comment by PericlesHat** [comment]
> I also meet the same problem, I find that tree.search_radius_vector_3d(point,0.001) return idx = [], so when I try to get idx[0], it has a bug.

@ShunChengWu I got the same problem as this. `idx` returns `IntVector[]`. So `idx[0]` causes an IndexError.
However, unlike @YYLiuDLUT , my two shapes share the same lengths and `pth_obj` ends with `mesh.refined.v2.obj`. I think there's something wrong with this line `[k, idx, distance] = tree.search_radius_vector_3d(point,0.001)`, it generates an empty `idx`.

**Comment by ShunChengWu** [comment]
I will look into this issue soon.

**Comment by ShunChengWu** [comment]
There is an issue with the open3d kdtree. I have managed to overcome it by replacing it with knn_cuda. 
But the generating time needs around 5 hours. 

I am going to release the generated "color.align.ply" soon on our server., as well as the updated code.
But will need to wait a bit... likely after the next CVPR (18 June 2023)

Sorry for the waiting.

**Comment by ShunChengWu** [comment]
The problem should be solved with the new code.

**Comment by PericlesHat** [comment]
> The problem should be solved with the new code.

Thanks for your work.
