### ISSUE TITLE
Size mismatched (20 v.s. 160)

### ISSUE THREAD

**Issue by Kenneth-Wong** [ShunChengWu/3DSSG#9]
The checkpoint you provided seems to be trained with 20 object classes. However, the data generated with the script contains 160 classes. I guess it's controlled by the files/classes160.txt. Can you provide another file that contains the 20 classes you use? Thanks.

**Comment by ShunChengWu** [comment]
Hi,

you need to set label type to ScanNet when generating the data 
`--label_type  ScanNet20`

The checkpoint we provided is trained with 20 labels.

**Comment by Kenneth-Wong** [comment]
I see. I think you should add a choice in the ```--label_type``` in gen_data_gt.py. Thanks.
